//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpticienMvcApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class LignOpVente
    {
        public int ID { get; set; }
        public int OperationVenteID { get; set; }
        public int ProduitID { get; set; }
        public int Quantite { get; set; }
        public decimal PrixUnitaireVendu { get; set; }
        public decimal Remise { get; set; }
        public string Ligne_OD_SPH { get; set; }
        public string Ligne_OD_CYL { get; set; }
        public string Ligne_OD_AXE { get; set; }
        public string Ligne_OD_ADD { get; set; }
        public string Ligne_OG_SPH { get; set; }
        public string Ligne_OG_CYL { get; set; }
        public string Ligne_OG_AXE { get; set; }
        public string Ligne_OG_ADD { get; set; }
        public string Ligne_EP_VL { get; set; }
        public string Ligne_H_Prog { get; set; }
    
        public virtual OperationVente OperationVente { get; set; }
        public virtual Produit Produit { get; set; }
    }
}
