//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpticienMvcApp
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class OperationVente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OperationVente()
        {
            this.LignOpVente = new HashSet<LignOpVente>();
            this.PAIEMENT = new HashSet<PAIEMENT>();
        }
    
        public int ID { get; set; }
        public string NumeroOp { get; set; }
        public System.DateTime DateDeVente { get; set; }
        public Nullable<System.DateTime> DateLivrisonPrevu { get; set; }
        public string Remarque { get; set; }
        public int ClientID { get; set; }
        public Nullable<int> OrdID { get; set; }
        public Nullable<int> VendeurID { get; set; }
        public string Statut { get; set; }
    
        [NotMapped]
        public decimal MontantTotal { get; set; }
    
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LignOpVente> LignOpVente { get; set; }
        public virtual Ordonnance Ordonnance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAIEMENT> PAIEMENT { get; set; }
        public virtual Vendeur Vendeur { get; set; }
    }
}
