//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpticienMvcApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OPTICIENEntities : DbContext
    {
        public OPTICIENEntities()
            : base("name=OPTICIENEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategorieProduit> CategorieProduit { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<DetailMonture> DetailMonture { get; set; }
        public virtual DbSet<DetailVerre> DetailVerre { get; set; }
        public virtual DbSet<LignOpVente> LignOpVente { get; set; }
        public virtual DbSet<Medecin> Medecin { get; set; }
        public virtual DbSet<OperationVente> OperationVente { get; set; }
        public virtual DbSet<Ordonnance> Ordonnance { get; set; }
        public virtual DbSet<PAIEMENT> PAIEMENT { get; set; }
        public virtual DbSet<Produit> Produit { get; set; }
        public virtual DbSet<Vendeur> Vendeur { get; set; }
    }
}
