//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpticienMvcApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ordonnance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ordonnance()
        {
            this.OperationVente = new HashSet<OperationVente>();
        }
    
        public int ID { get; set; }
        public System.DateTime DateDePrescription { get; set; }
        public Nullable<System.DateTime> DateExpiration { get; set; }
        public string OD_VL_SPH { get; set; }
        public string OD_VL_CYL { get; set; }
        public string OD_VL_AXE { get; set; }
        public string OD_VL_ADD { get; set; }
        public string OD_VL_EP { get; set; }
        public string OD_VL_H { get; set; }
        public string OD_VL_DAIM { get; set; }
        public string OG_VL_SPH { get; set; }
        public string OG_VL_CYL { get; set; }
        public string OG_VL_AXE { get; set; }
        public string OG_VL_ADD { get; set; }
        public string OG_VL_EP { get; set; }
        public string OG_VL_H { get; set; }
        public string OG_VL_DAIM { get; set; }
        public string OD_VP_SPH { get; set; }
        public string OD_VP_CYL { get; set; }
        public string OD_VP_AXE { get; set; }
        public string OD_VP_ADD { get; set; }
        public string OD_VP_EP { get; set; }
        public string OD_VP_H { get; set; }
        public string OD_VP_DAIM { get; set; }
        public string OG_VP_SPH { get; set; }
        public string OG_VP_CYL { get; set; }
        public string OG_VP_AXE { get; set; }
        public string OG_VP_ADD { get; set; }
        public string OG_VP_EP { get; set; }
        public string OG_VP_H { get; set; }
        public string OG_VP_DAIM { get; set; }
        public Nullable<int> MedecinID { get; set; }
    
        public virtual Medecin Medecin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperationVente> OperationVente { get; set; }
    }
}
