//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpticienMvcApp
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    [MetadataType(typeof(PAIEMENTMetadata))]
    public partial class PAIEMENT
    {
        public int ID { get; set; }
        public System.DateTime DatePaiement { get; set; }
        public string ModeDePaiement { get; set; }
        public decimal MontantPaye { get; set; }
        public int OpVenteID { get; set; }
        public string ReferencePaiement { get; set; }
    
        public virtual OperationVente OperationVente { get; set; }
    }

    public class PAIEMENTMetadata
    {
        [Required(ErrorMessage = "Le champ ID est requis.")]
        public int ID { get; set; }

        [Required(ErrorMessage = "La date de paiement est requise.")]
        [Display(Name = "Date de Paiement")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime DatePaiement { get; set; }

        [Required(ErrorMessage = "Le mode de paiement est requis.")]
        [Display(Name = "Mode de Paiement")]
        public string ModeDePaiement { get; set; }

        [Required(ErrorMessage = "Le montant payé est requis.")]
        [Display(Name = "Montant Payé")]
        [DisplayFormat(DataFormatString = "{0:N2}", ApplyFormatInEditMode = true)]
        [Range(0.01, double.MaxValue, ErrorMessage = "Le montant doit être supérieur à 0.")]
        public decimal MontantPaye { get; set; }

        [Required(ErrorMessage = "L'opération de vente est requise.")]
        [Display(Name = "Opération de Vente")]
        public int OpVenteID { get; set; }

        [Display(Name = "Référence de Paiement")]
        public string ReferencePaiement { get; set; }
    }
}
