//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpticienMvcApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produit()
        {
            this.LignOpVente = new HashSet<LignOpVente>();
        }
    
        public int ID { get; set; }
        public string Reference { get; set; }
        public string Designation { get; set; }
        public int CategorieID { get; set; }
        public decimal PrixUnitaire { get; set; }
        public decimal TauxTVA { get; set; }
        public string Fabricant { get; set; }
        public bool Actif { get; set; }
    
        public virtual CategorieProduit CategorieProduit { get; set; }
        public virtual DetailMonture DetailMonture { get; set; }
        public virtual DetailVerre DetailVerre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LignOpVente> LignOpVente { get; set; }
    }
}
